### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by hlapp** [hdr-bgnn/BGNN_Snakemake#2]
There should be an open-source license attached to this repo, so that rights and terms of reuse are clear.

Consider the following resources if it's not clear which license to choose and how:

- [Choose a License](https://choosealicense.com)
- Morin, A., Urban, J., & Sliz, P. (2012). A Quick Guide to Software Licensing for the Scientist-Programmer. PLoS Computational Biology, 8(7), e1002598. <http://dx.doi.org/10.1371/journal.pcbi.1002598>

**Comment by thibaulttabarin** [comment]
I have no idea what to do with the license. If someone knows what to do please let me know.

**Comment by johnbradley** [comment]
@thibaulttabarin A license in a GitHub repo is just a text file named LICENSE that contains the text of the license.
Once a decision is made about which license to use GitHub makes it really easy to add a license:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by thibaulttabarin** [comment]
For this issue of licensing, my guess is we will go for Mit licensing like Phenoscape (BTW who should take the decision). But since I am using the code from other groups what should I do? The 2 other groups I am using the code from, didn't put any licensing so they are copyright protected by default as far as I understand. So I suppose I need to contact them to change their copy right to the MIT licence and then license this repo? Maybe something to put on discourse? what are your thoughts/experiences on that?

**Comment by johnbradley** [comment]
Getting feedback in discourse sounds like a good idea to me.

**Comment by hlapp** [comment]
@thibaulttabarin for the code you wrote, depending on what your contract says the decision can be made by you, or by those who contracted you. (Contracts differ by whether all intellectual property is automatically assigned to the contractor [you], or to those for whom you contract [NEON or Batelle].)

For code written by people at other institutions, indeed they will need to be contacted and will need to approve the license. It will depend on the institution and the status of the contributor as to whether they themselves can grant those rights, or whether the PI or some other entity at the institution can do so.

**Comment by hlapp** [comment]
On inspection, it looks like all the code in this repo is by @thibaulttabarin. So you should clear up who owns the copyright. If it's you, you can go ahead and put it under the MIT license.

**Comment by thibaulttabarin** [comment]
I am not sure but I think the issue is that the snakmake workflow uses containers that run the code from Drexel https://github.com/hdr-bgnn/drexel_metadata and Virginia tech https://github.com/hdr-bgnn/BGNN-trait-segmentation. I suppose in this case we need to have the correct license on those 2 repositories. I have contacted Anju and Jane to put licenses on their codes.

**Comment by hlapp** [comment]
No we don't, because these containers are used by, but not in any way part of the codebase here. Thus, the license applied here has no risk of possibly extending to those containers.

(For example, if this code were to invoke MS Excel somewhere, by no means would this imply that the license here would extend to MS Excel.)

**Comment by hlapp** [comment]
Fixed in #14.
